apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlinebanking
  labels:
    product: actimize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp1
      tier: web
  template:
    metadata:
      labels:
        app: bankapp1
        tier: web
    spec:
      containers:
      - name: bankcontainer
        image: juanjograk/juanbankingapp
        ports:
        - containerPort: 8989
        resources:
          limits:  
            cpu: 900m
            memory: 700Mi             
          requests: 
            cpu: 500m
            memory: 400Mi
