apiVersion: v1
kind: Service
metadata:
  name: onlinebanking
  labels:
    app: actimize
spec:
  ports:
   - name: bankcontainer
     port: 8989
     targetPort: 8989
  type: NodePort
  selector:
    app: bankapp1
    tier: web
